### ISSUE TITLE
Ergonomics regarding iter_records

### ISSUE THREAD

**Issue by Uinelj** [jedireza/warc#27]
Hi,

I've been using warc <0.3 and am recently updating my project to use the new 0.3 API, but I feel that some handy methods that were present in <0.3 are absent now, namely being able to iterate on `WarcReader`. 

There seems to be replacements with `iter_records`, `iter_raw_records` and `stream_records`, and I welcome them since the library provides more flexibility now, but I worry about the ergonomics, since the return types of these three methods are private, constraining users to use either `Box` or generics with `impl I: Iterator<Item = ...>`, adding easily avoidable boilerplate code.

Is there something planned to address this or should I write abstractions in my project?

**Comment by jedireza** [comment]
Hi @Uinelj thanks for posting. @jhwgh1968 has been driving the recent changes, so I'll defer to them. My position is if a thing is idiomatic and doesn't cost much (or anything) I'm generally for it.

**Comment by Uinelj** [comment]
Thanks for your prompt response.

I've also found other locations where public interfaces returned private types, which makes some operations awkward.
As an example, if someone wants to get the headers of a specific record:

```rs
let headers = record.headers; // ERR:  headers field is private
let headers = record.headers(); // ERR: there's no getter for headers
let headers = record.into_raw_parts().0;  // OK: takes ownership and returns body too, however we can't use the type returned since it's private (RawRecordHeader) and hence it may be hard/awkward to store the variable in structs
let headers, _ = record.into_raw_parts().0.headers; // OK: now we have something that can be passerd around freely, but the ergonomics are weird
```

I may be misguided in the way I use the library, and in that case I'd be happy to know how to better use the API (and improve the docs with more examples to guide potential users), or otherwise I'd be interested in helping to improve docs/examples or API ergonomics.

**Comment by jhwgh1968** [comment]
Hi @Uinelj,

For your original question, it seems I forgot to document the iterator structs. My bad! I will correct that in a PR soon.

For your second question, my intention with this re-design is to focus on parsing records and asking them questions, rather than looking inside. That way, invariants about correctness can be upheld, and storage can be kept flexible. Not everything is kept as a string or integer, for instance.

Iterating all headers -- and treating them all the same in the iterator -- breaks that abstraction. My goal is to make iteration unnecessary by having the user think about their problem differently, depending on what it is.

* Are you iterating headers to get basic information? There are getters on common fields (id, date, etc)
* Are you iterating headers to look for a specific one? Use `record.header(h)` and pass in a `WarcHeader` enum. It'll return the value, or `None` if it does not exist.
* Are you going to transform the record in some way? Use the getter and setter methods, and then body methods based on what you want to do.
* Are you gathering up all information about a record to turn it into another format? Use `into_raw_parts` to make it into a `RawRecord` which is a 100% transparent type that can match the serialization format exactly.

If you still think you need iteration, please explain a little more about your use case.

**Comment by Uinelj** [comment]
Hello,

Thank you for your fast and complete response.

I have refactored my code to better comply with your API design, and your thorough explanations gave me the context I needed :)

I'll close the issue for now, thanks again for your time!
