### ISSUE TITLE
Streaming seems busted?

### ISSUE THREAD

**Issue by maxcountryman** [jedireza/warc#37]
Hi there,

I'm unable to figure out how to leverage the streaming API. I spent some time trying to build this into a larger project only to pare it down to a very simple program.

What I end up seeing is this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseHeaders(Error(([13, 10], Tag)))'
```

Note that the same WARC file is processed without issue using the buffered API; I'd be fine to use this but because I want to wrap the WARC reader with my own `impl Iterator` it's tricky to hold onto the reader in a struct and call it within `fn next(&mut self)` and so the signature of `stream_records` seemed to be a workaround.

However I've run into the above issue (always directly after the first header). You should be able to reproduce with wget:

```
$ wget --warc-file example 'https://example.com'
```

If you then pass this file, `example.warc.gz` through the streaming API the error occurs with a program like so:

```rust
    let mut reader =
        WarcReader::from_path_gzip(PathBuf::from_str("example.warc.gz").unwrap()).unwrap();
    while let Some(record) = reader.stream_records().next_item() {
        dbg!(record.unwrap().into_buffered());
    }
```

The bytes, `13` and `10`, are almost certainly the carriage return and line feed the parser is looking for, but perhaps the assumptions about the positioning aren't quite right? Specifically the logic in `next_item` seems suspicious.

**Comment by maxcountryman** [comment]
The issue is that I'm not binding the result of `reader.stream_records` before looping over it and so the internal tracking of first record read is continually reset to `false`, leading to this error. If I rewrite this slightly to bind as such it indeed runs as expected.

That said, I'm still struggling to wrap this in a struct that `impl`s `Iterator` over the stream itself, given the lifetime requirement and likewise with the buffered variation (because as I previously mentioned it needs an owned value of self).

**Comment by jedireza** [comment]
@jhwgh1968 probably knows more about streaming than myself. Hopefully they have time to comment on it.

I just saw your project on HN and thought it sounded familiar 😄

**Comment by maxcountryman** [comment]
@jedireza thanks for chiming in--I ended up working around this by [separating the ownership of the reader and the iterator into two structs](https://github.com/maxcountryman/warc-parquet/blob/5a742b641ee27551d967e23def9b425e5c589eb0/src/reader.rs#L93-L123) (much like you all are doing in this crate). I suspect that's probably the right pattern? (Forgive me, I have a lot still to learn about Rust so some of these patterns are not my intuition.)

**Comment by jhwgh1968** [comment]
Hi @maxcountryman,

Although I had to name the method `next_item` instead of using `next` to deal with the difference between data and records, the Streaming API still tries to remain composable.

The code you highlighted is exactly how the Streaming API is supposed to be used for the use case of "mapping" each record to something else lazily. If the user wants to do an explicit loop rather than an iterator structure, they can use `iter_records()` as shown in the `read_gzip.rs` example.

Since I see you closed the issue, I presume your solution is satisfactory.

As a side note, I would mention that the explicit if in your iterator code could be simplified. Just replace it with [`and_then()`](https://doc.rust-lang.org/stable/std/option/enum.Option.html#method.and_then), turning your current block on the `Some` branch into a closure. Unless you think what you have is more readable, of course. I am not 100% sure, but I think clippy has a lint that would catch this.

If you have other questions, let me know.
